-- CoastCast v5.0 Launch Backend
-- Supabase/Postgres foundation for real accounts, server-side Premium access,
-- family sharing, complimentary/lifetime grants, admin tools and purchase records.
-- Run after SUPABASE_SETUP.sql. Safe to re-run where noted.

create extension if not exists pgcrypto;

-- ---------- Admins ----------
create table if not exists public.coastcast_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('owner','admin','support')),
  created_at timestamptz not null default now()
);
alter table public.coastcast_admins enable row level security;
drop policy if exists "admin can read own admin row" on public.coastcast_admins;
create policy "admin can read own admin row" on public.coastcast_admins
for select to authenticated using (auth.uid() = user_id);

-- ---------- Direct entitlements ----------
create table if not exists public.coastcast_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  access_level text not null default 'free' check (access_level in ('free','premium')),
  source text not null default 'free' check (source in ('free','play','complimentary','lifetime','promo','beta')),
  status text not null default 'active' check (status in ('active','grace','expired','revoked')),
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  granted_by uuid references auth.users(id) on delete set null,
  note text,
  updated_at timestamptz not null default now()
);
alter table public.coastcast_entitlements enable row level security;
drop policy if exists "users can read own entitlement" on public.coastcast_entitlements;
create policy "users can read own entitlement" on public.coastcast_entitlements
for select to authenticated using (auth.uid() = user_id);

-- ---------- Family membership ----------
create table if not exists public.coastcast_family_members (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  member_user_id uuid references auth.users(id) on delete cascade,
  invite_email text,
  status text not null default 'invited' check (status in ('invited','active','removed','expired')),
  created_at timestamptz not null default now(),
  joined_at timestamptz,
  removed_at timestamptz,
  unique(owner_id, member_user_id)
);
create unique index if not exists coastcast_family_pending_unique
on public.coastcast_family_members(owner_id, lower(invite_email))
where member_user_id is null and status='invited';
create unique index if not exists coastcast_family_one_active_membership
on public.coastcast_family_members(member_user_id)
where member_user_id is not null and status='active';

alter table public.coastcast_family_members enable row level security;
drop policy if exists "family users can read membership" on public.coastcast_family_members;
create policy "family users can read membership" on public.coastcast_family_members
for select to authenticated using (auth.uid() = owner_id or auth.uid() = member_user_id);

-- ---------- Audit trail ----------
create table if not exists public.coastcast_entitlement_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  access_level text,
  source text,
  expires_at timestamptz,
  actor_id uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);
alter table public.coastcast_entitlement_audit enable row level security;
drop policy if exists "users can read own entitlement audit" on public.coastcast_entitlement_audit;
create policy "users can read own entitlement audit" on public.coastcast_entitlement_audit
for select to authenticated using (auth.uid() = user_id);

-- ---------- Google Play purchase ledger (backend only) ----------
create table if not exists public.coastcast_play_purchases (
  token_hash text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  package_name text not null,
  product_id text not null,
  subscription_state text,
  latest_expiry timestamptz,
  order_id text,
  raw_summary jsonb not null default '{}'::jsonb,
  verified_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.coastcast_play_purchases enable row level security;
-- Intentionally no client read/write policies.

-- ---------- Push subscriptions (future closed-app alerts) ----------
create table if not exists public.coastcast_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_secret text not null,
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.coastcast_push_subscriptions enable row level security;
drop policy if exists "users manage own push subscriptions" on public.coastcast_push_subscriptions;
create policy "users manage own push subscriptions" on public.coastcast_push_subscriptions
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- Helpers ----------
create or replace function public.coastcast_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists(select 1 from public.coastcast_admins a where a.user_id = auth.uid());
$$;
grant execute on function public.coastcast_is_admin() to authenticated;

create or replace function public.coastcast_direct_entitlement_valid(e public.coastcast_entitlements)
returns boolean
language sql
stable
as $$
  select e.access_level='premium'
    and e.status in ('active','grace')
    and (e.expires_at is null or e.expires_at > now());
$$;

-- Effective access resolves direct paid/admin grants first, then Family Premium.
create or replace function public.coastcast_my_access()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  uid uuid := auth.uid();
  direct_row public.coastcast_entitlements%rowtype;
  fam record;
  admin_flag boolean := false;
begin
  if uid is null then
    return jsonb_build_object('signed_in',false,'premium',false,'source','free','status','anonymous','is_admin',false);
  end if;
  select exists(select 1 from public.coastcast_admins where user_id=uid) into admin_flag;

  select * into direct_row from public.coastcast_entitlements where user_id=uid limit 1;
  if found and public.coastcast_direct_entitlement_valid(direct_row) then
    return jsonb_build_object(
      'signed_in',true,'premium',true,'source',direct_row.source,'status',direct_row.status,
      'starts_at',direct_row.starts_at,'expires_at',direct_row.expires_at,'is_admin',admin_flag
    );
  end if;

  select fm.owner_id, e.source as owner_source, e.expires_at as owner_expires
  into fam
  from public.coastcast_family_members fm
  join public.coastcast_entitlements e on e.user_id=fm.owner_id
  where fm.member_user_id=uid and fm.status='active'
    and public.coastcast_direct_entitlement_valid(e)
  order by fm.joined_at desc nulls last
  limit 1;
  if found then
    return jsonb_build_object(
      'signed_in',true,'premium',true,'source','family','status','active',
      'family_owner_id',fam.owner_id,'expires_at',fam.owner_expires,'is_admin',admin_flag
    );
  end if;

  return jsonb_build_object('signed_in',true,'premium',false,'source','free','status','active','is_admin',admin_flag);
end;
$$;
grant execute on function public.coastcast_my_access() to authenticated;

-- ---------- Family RPCs ----------
create or replace function public.coastcast_family_invite(p_email text)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  uid uuid := auth.uid();
  email_norm text := lower(trim(p_email));
  owner_ent public.coastcast_entitlements%rowtype;
  existing_user uuid;
  row_id bigint;
begin
  if uid is null then raise exception 'Sign in required'; end if;
  if email_norm !~ '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$' then raise exception 'Enter a valid email'; end if;

  select * into owner_ent from public.coastcast_entitlements where user_id=uid;
  if not found or not public.coastcast_direct_entitlement_valid(owner_ent) then
    raise exception 'A direct Premium entitlement is required to invite family';
  end if;
  if owner_ent.source='family' then raise exception 'Family members cannot create another family group'; end if;

  select id into existing_user from auth.users where lower(email)=email_norm limit 1;

  if existing_user is null then
    select id into row_id from public.coastcast_family_members
      where owner_id=uid and lower(invite_email)=email_norm and status='invited' limit 1;
    if row_id is null then
      insert into public.coastcast_family_members(owner_id,member_user_id,invite_email,status)
      values(uid,null,email_norm,'invited') returning id into row_id;
    end if;
  else
    insert into public.coastcast_family_members(owner_id,member_user_id,invite_email,status,joined_at,removed_at)
    values(uid,existing_user,email_norm,'active',now(),null)
    on conflict (owner_id, member_user_id) do update
      set invite_email=excluded.invite_email,status='active',joined_at=coalesce(public.coastcast_family_members.joined_at,now()),removed_at=null
    returning id into row_id;
  end if;
  return jsonb_build_object('ok',true,'id',row_id,'email',email_norm,'status',case when existing_user is null then 'invited' else 'active' end);
end;
$$;
grant execute on function public.coastcast_family_invite(text) to authenticated;

create or replace function public.coastcast_family_accept()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  uid uuid := auth.uid();
  email_norm text;
  invite_id bigint;
begin
  if uid is null then raise exception 'Sign in required'; end if;
  if exists(select 1 from public.coastcast_family_members where member_user_id=uid and status='active') then
    return jsonb_build_object('ok',true,'accepted',0,'message','Already in an active Family Crew');
  end if;
  select lower(email) into email_norm from auth.users where id=uid;
  select id into invite_id from public.coastcast_family_members
    where status='invited' and member_user_id is null and lower(invite_email)=email_norm
    order by created_at asc limit 1;
  if invite_id is null then return jsonb_build_object('ok',true,'accepted',0); end if;
  update public.coastcast_family_members set member_user_id=uid,status='active',joined_at=now(),removed_at=null where id=invite_id;
  return jsonb_build_object('ok',true,'accepted',1,'id',invite_id);
end;
$$;
grant execute on function public.coastcast_family_accept() to authenticated;

create or replace function public.coastcast_family_list()
returns table(id bigint, member_user_id uuid, email text, status text, joined_at timestamptz)
language sql
stable
security definer
set search_path = public, auth
as $$
  select fm.id, fm.member_user_id,
         coalesce(u.email,fm.invite_email) as email,
         fm.status, fm.joined_at
  from public.coastcast_family_members fm
  left join auth.users u on u.id=fm.member_user_id
  where fm.owner_id=auth.uid() and fm.status in ('invited','active')
  order by fm.created_at;
$$;
grant execute on function public.coastcast_family_list() to authenticated;

create or replace function public.coastcast_family_remove(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  update public.coastcast_family_members set status='removed',removed_at=now()
  where id=p_id and owner_id=auth.uid();
  if not found then raise exception 'Family member not found'; end if;
  return jsonb_build_object('ok',true);
end;
$$;
grant execute on function public.coastcast_family_remove(bigint) to authenticated;

-- ---------- Admin RPCs ----------
create or replace function public.coastcast_admin_list_access(p_limit integer default 50)
returns table(user_id uuid,email text,access_level text,source text,status text,expires_at timestamptz,note text)
language plpgsql
stable
security definer
set search_path = public, auth
as $$
begin
  if not public.coastcast_is_admin() then raise exception 'Admin access required'; end if;
  return query
  select u.id,u.email,coalesce(e.access_level,'free'),coalesce(e.source,'free'),coalesce(e.status,'active'),e.expires_at,e.note
  from auth.users u left join public.coastcast_entitlements e on e.user_id=u.id
  order by u.created_at desc limit greatest(1,least(coalesce(p_limit,50),200));
end;
$$;
grant execute on function public.coastcast_admin_list_access(integer) to authenticated;

create or replace function public.coastcast_admin_grant_access(p_email text,p_source text,p_expires_at timestamptz default null,p_note text default null)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  target uuid;
  src text := lower(trim(p_source));
begin
  if not public.coastcast_is_admin() then raise exception 'Admin access required'; end if;
  if src not in ('complimentary','lifetime','promo','beta') then raise exception 'Invalid admin grant source'; end if;
  select id into target from auth.users where lower(email)=lower(trim(p_email)) limit 1;
  if target is null then raise exception 'No CoastCast account exists for that email'; end if;
  if src='lifetime' then p_expires_at := null; end if;
  insert into public.coastcast_entitlements(user_id,access_level,source,status,starts_at,expires_at,granted_by,note,updated_at)
  values(target,'premium',src,'active',now(),p_expires_at,auth.uid(),p_note,now())
  on conflict(user_id) do update set access_level='premium',source=excluded.source,status='active',starts_at=now(),expires_at=excluded.expires_at,granted_by=auth.uid(),note=excluded.note,updated_at=now();
  insert into public.coastcast_entitlement_audit(user_id,action,access_level,source,expires_at,actor_id,note)
  values(target,'grant','premium',src,p_expires_at,auth.uid(),p_note);
  return jsonb_build_object('ok',true,'user_id',target,'source',src,'expires_at',p_expires_at);
end;
$$;
grant execute on function public.coastcast_admin_grant_access(text,text,timestamptz,text) to authenticated;

create or replace function public.coastcast_admin_revoke_access(p_email text,p_note text default null)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare target uuid;
begin
  if not public.coastcast_is_admin() then raise exception 'Admin access required'; end if;
  select id into target from auth.users where lower(email)=lower(trim(p_email)) limit 1;
  if target is null then raise exception 'No CoastCast account exists for that email'; end if;
  update public.coastcast_entitlements set status='revoked',updated_at=now(),note=coalesce(p_note,note) where user_id=target;
  insert into public.coastcast_entitlement_audit(user_id,action,access_level,source,actor_id,note)
  select target,'revoke',access_level,source,auth.uid(),p_note from public.coastcast_entitlements where user_id=target;
  return jsonb_build_object('ok',true,'user_id',target);
end;
$$;
grant execute on function public.coastcast_admin_revoke_access(text,text) to authenticated;

-- IMPORTANT BOOTSTRAP STEP:
-- After creating YOUR CoastCast owner account, copy its UUID from Authentication > Users
-- and run this once, replacing the placeholder:
-- insert into public.coastcast_admins(user_id,role) values ('YOUR-USER-UUID','owner') on conflict(user_id) do update set role='owner';
