-- CoastCast 4.0 entitlement foundation (Supabase/Postgres)
-- Run only when you are ready to add account entitlements.
-- IMPORTANT: no client-side INSERT/UPDATE policies are created for entitlements.
-- Paid/family/complimentary grants should be written by a trusted backend/service role.

create table if not exists public.coastcast_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  access_level text not null default 'free' check (access_level in ('free','premium')),
  source text not null default 'free' check (source in ('free','play','family','complimentary','lifetime','promo','beta')),
  status text not null default 'active' check (status in ('active','grace','expired','revoked')),
  family_owner_id uuid references auth.users(id) on delete set null,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  granted_by uuid references auth.users(id) on delete set null,
  note text,
  updated_at timestamptz not null default now()
);

alter table public.coastcast_entitlements enable row level security;
drop policy if exists "users can read own entitlement" on public.coastcast_entitlements;
create policy "users can read own entitlement"
  on public.coastcast_entitlements for select
  using (auth.uid() = user_id);

create table if not exists public.coastcast_family_members (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  member_user_id uuid references auth.users(id) on delete cascade,
  invite_email text,
  status text not null default 'invited' check (status in ('invited','active','removed','expired')),
  created_at timestamptz not null default now(),
  joined_at timestamptz,
  unique(owner_id, member_user_id)
);

alter table public.coastcast_family_members enable row level security;
drop policy if exists "family users can read their membership" on public.coastcast_family_members;
create policy "family users can read their membership"
  on public.coastcast_family_members for select
  using (auth.uid() = owner_id or auth.uid() = member_user_id);

create table if not exists public.coastcast_entitlement_audit (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  access_level text,
  source text,
  expires_at timestamptz,
  actor_id uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

alter table public.coastcast_entitlement_audit enable row level security;
drop policy if exists "users can read own entitlement audit" on public.coastcast_entitlement_audit;
create policy "users can read own entitlement audit"
  on public.coastcast_entitlement_audit for select
  using (auth.uid() = user_id);

-- No INSERT/UPDATE/DELETE policies are intentionally granted to normal users.
-- Use a trusted backend/service role for Google Play validation, family management,
-- complimentary grants, revocations and audit logging.
